### ISSUE TITLE
6.6.5版本运行闪退

### ISSUE THREAD

**Issue by Rebuilding127** [yoshiko2/Movie_Data_Capture#1043]
```log
ERROR:root:DLL load failed while importing _dlib_pybind11: 动态链接库(DLL)初始化例程失败。
Traceback (most recent call last):
  File "Movie_Data_Capture.py", line 718, in <module>
  File "Movie_Data_Capture.py", line 640, in main
  File "Movie_Data_Capture.py", line 459, in create_data_and_move
  File "core.py", line 982, in core_main
  File "core.py", line 512, in add_mark
  File "core.py", line 527, in add_mark_thread
  File "core.py", line 575, in add_to_pic
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

**Comment by darkj2k** [comment]
Traceback (most recent call last):
  File "configparser.py", line 791, in get
  File "collections\__init__.py", line 986, in __getitem__
  File "collections\__init__.py", line 978, in __missing__
KeyError: 'target_language'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Movie_Data_Capture.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "scraper.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ADC_function.py", line 304, in <module>
  File "config.py", line 286, in get_target_language
  File "configparser.py", line 794, in get
configparser.NoOptionError: No option 'target_language' in section: 'translate'
[6756] Failed to execute script 'Movie_Data_Capture' due to unhandled exception!
