### ISSUE TITLE
群晖dsm7.2，源码方式运行，之前一直正常，今天突然报错了

### ISSUE THREAD

**Issue by zhengweiqing** [yoshiko2/Movie_Data_Capture#1098]
如题，之前用源码方式运行一直正常，今天好奇心驱使下，下载了一个linux版本运行了一下出错，然后再运行源码版本的就开始报下边的错误了，我刚开始以为是 “/root/.local/share/mdc/c_number.json” 这个文件不存在，新建了一个也不行，后来连目录都删除了还是报这个错误。

root@x:/volume1/mdc/6.6.7# python ./Movie_Data_Capture.py
[*]================= Movie Data Capture =================
[*]                        6.6.7
[*]======================================================
[*] - Linux-4.4.302+-x86_64-with-glibc2.34
[*] - x86_64 - Python-3.8.15
[*]======================================================
[*] - 严禁在墙内宣传本项目 -
[*]======================================================
[+]Start at 2023-10-10 08:49:44
[+]Load Config file '/volume1/mdc/6.6.7/config.ini'.
[+]Enable debug
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[+]Find 3 movies.
[*]======================================================
[!]                - 33.3% [1/3] -             08:49:44
[!] [FOCS-125] As Number Processing for '/volume4/12T_Emby/日韩/有码/2023-10/FOCS-125-C/FOCS-125-C.mp4'
[+]select javbus
list index out of range
[+]select airav
list index out of range
[+]select fanza
[+]select xcity
list index out of range
[+]select mgstage
'NoneType' object has no attribute 'xpath'
[+]select avsox
[+]select jav321
[+]Find movie [FOCS-125] metadata on website 'jav321'
Traceback (most recent call last):
  File "./Movie_Data_Capture.py", line 720, in <module>
    main(args)
  File "./Movie_Data_Capture.py", line 642, in main
    create_data_and_move(movie_path, zero_op, no_net_op, oCC)
  File "./Movie_Data_Capture.py", line 461, in create_data_and_move
    core_main(movie_path, n_number, oCC)
  File "/volume1/docker/mdc/6.6.7/core.py", line 845, in core_main
    json_data = get_data_from_json(number, oCC, specified_source, specified_url)  # 定义番号
  File "/volume1/docker/mdc/6.6.7/scraper.py", line 196, in get_data_from_json
    (Path.home() / '.local' / 'share' / 'mdc' / 'c_number.json').read_text(encoding="utf-8"))
  File "/usr/lib/python3.8/pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/mdc/c_number.json'

**Comment by zhengweiqing** [comment]
没有人能回复一下吗？
