### ISSUE TITLE
4.5.2版本javdb依然无法刮削

### ISSUE THREAD

**Issue by kglife** [yoshiko2/Movie_Data_Capture#464]
javdb仍无法刮削，所有片子都提示not in list，应该是上一个issues的中ifunboy提到的

“javdb.com已经启用cloudflare五秒盾，建议添加cookie选项。
临时解决，建议将JAVDB.PY 源码内 javdb4.com改为javdb8.com。javdb8.com暂时没有 防爬虫。”

**Comment by kglife** [comment]
测试将JAVDB.PY 源码内 javdb4.com改为javdb8.com， javdb.com改为javdb8.com仍报错 not in list

**Comment by ifunboy** [comment]
提供测试番号

**Comment by ifunboy** [comment]
试下用作者最新的代码，域名已经替换了。
可以尝试先用电脑浏览器打开javdb8.com，并点击同意。
刚才测试了一下没问题。
![1](https://user-images.githubusercontent.com/11016210/116353829-04f21980-a82a-11eb-9083-5367b88e5f19.png)

**Comment by kglife** [comment]
![QQ图片20210428152308](https://user-images.githubusercontent.com/82629056/116363472-bf3b4e00-a835-11eb-8df8-7817616f6752.png)
测试修改后不开梯子可以刮削，开了梯子反而报错，感谢了兄弟~

**Comment by TonyShu1218** [comment]
4.6.1依然無法刮削 [list index out of range]

**Comment by ifunboy** [comment]
JAVDB，FC2不可用。FC2需登陆网站会员，目前程序未支持登陆。

**Comment by xingfanxia** [comment]
javdb 4.6.3无法刮削 `list index out of range`

```[*]================== AV Data Capture ===================
[*]                        4.6.3
[*]======================================================
[+]Enable debug
[+]Find 18 movies
[!] - 5.55% [1/18] -
[!]Making Data for [/mnt/test/jav_newp/tbp/adad/MIUM-699.mp4], the number is [MIUM-699]
[+]select javbus
list index out of range
list index out of range
[+]select javdb
list index out of range
[+]select airav
[+]select fanza
[+]select xcity
[+]select mgstage
[+]select fc2
list index out of range
[+]select avsox
[+]select jav321
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 188, in <module>
  File "AV_Data_Capture.py", line 90, in create_data_and_move
  File "core.py", line 730, in core_main
  File "core.py", line 123, in get_data_from_json
  File "multiprocessing/pool.py", line 771, in get
  File "multiprocessing/pool.py", line 125, in worker
  File "WebCrawler/jav321.py", line 25, in main
  File "WebCrawler/jav321.py", line 114, in get_outline
IndexError: list index out of range
[660805] Failed to execute script AV_Data_Capture```

**Comment by xingfanxia** [comment]
javbus也出了这个问题
```
[!] - 33.3% [4/12] -
[!]Making Data for [/mnt/test/jav_newp/tbp/adad/ssis-062-C.mp4], the number is [ssis-062]
[+]select javbus
list index out of range
list index out of range
```
