### ISSUE TITLE
Organize Genres已失败

### ISSUE THREAD

**Issue by dayunnas** [yoshiko2/Movie_Data_Capture#474]
Method not found: 'System.Collections.Generic.Dictionary`2<system.string,system.string> MediaBrowser.Controller.Entities.BaseItem.get_ProviderIds()'.
at Jellyfin.Plugin.AVDC.ScheduledTasks.OrganizeGenresTask.&lt;&gt;c.<execute>b__12_0(BaseItem item)
at System.Linq.Enumerable.WhereArrayIterator`1.ToList()
at Jellyfin.Plugin.AVDC.ScheduledTasks.OrganizeGenresTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)</execute></system.string,system.string>

**Comment by dayunnas** [comment]
环境是emby 4.6.0.41测试版
