### ISSUE TITLE
Bad file descriptor error in 4.6.3

### ISSUE THREAD

**Issue by amourpower** [yoshiko2/Movie_Data_Capture#492]
HI, I am facing this error when I use 4.6.3. But it is fine when I run the same by 4.6.2. Any idea?

OS: MacOS 10.15.7
Python: 3.9.5

[*]================== AV Data Capture ===================
[*]                        4.6.3
[*]======================================================
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[+]Find 1 movies
[!] - 100.% [1/1] -
[!]Making Data for [/Volumes/good/ssis-066-C.mp4], the number is [ssis-066]
[-] [/Volumes/good/ssis-066-C.mp4] ERROR:
[-] 'javlib'
[+]Used 0.3s
[+]All finished!!!
Exception ignored in: <function Pool.__del__ at 0x7fcec9567310>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/queues.py", line 378, in put
    self._writer.send_bytes(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor

**Comment by philipzb** [comment]
大佬好，能不能增加群晖nas的教程啊，网上找的都不能用，谢谢🙏

**Comment by yoshiko2** [comment]
@philipzb [WIKI](https://github.com/yoshiko2/AV_Data_Capture/wiki#NAS%E7%9A%84%E9%A3%9F%E7%94%A8%E6%96%B9%E5%BC%8F)
