### ISSUE TITLE
闪退了，请问是缺环境还是怎么了，之前都在用的

### ISSUE THREAD

**Issue by leahakira** [yoshiko2/Movie_Data_Capture#665]
Traceback (most recent call last):
  File "Movie_Data_Capture.py", line 585, in <module>
  File "Movie_Data_Capture.py", line 497, in main
  File "Movie_Data_Capture.py", line 32, in check_update
KeyError: 'tag_name'

**Comment by lededev** [comment]
改配置文件config.ini试试
```ini
[update]
update_check=0

```

**Comment by leahakira** [comment]
谢谢，关了可以了，好奇怪
