### ISSUE TITLE
部分FC2文件名不会被程序识别处理

### ISSUE THREAD

**Issue by nceccy** [yoshiko2/Movie_Data_Capture#671]
以下分集文件在目录中不会被程序自动处理，相同FC2番号的其它分集被处理。当仅剩余这些文件时，程序显示`Find 0 movies`，随后立刻结束。
```
FC2-1267832-cd2.mp4
FC2-1267832-cd3.mp4
FC2-1351603-cd2.mp4
FC2-1454268-cd4.mp4
FC2-1551839-cd2.mp4
FC2-1551839-cd3.mp4
FC2-1619766-cd4.mp4
FC2-1761438-cd2.mp4
FC2-1772836-cd2.mp4
FC2-1784119-cd2.mp4
FC2-1817464-cd4.mp4
FC2-2212716-cd3.mp4
```

输出：
```
[*]================= Movie Data Capture =================
[*]                        6.0.1                         
[*]======================================================
[*] - Windows-10-10.0.19044-SP0 
[*] - AMD64 - Python-3.8.10
[*]======================================================
[*] - 严禁在墙内宣传本项目 - 
[*]======================================================
[+]Start at 2022-01-08 01:56:48
[+]Load Config file 'C:\Users\nceccy\Downloads\AVDC\config.ini'.
[+]Enable debug
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[+]Find 0 movies.
[*]======================================================
[+]Running time 0:00:00.059  End at 2022-01-08 01:56:48
[+]All finished!!!
```

使用命令行，为每个文件单独运行程序可以暂时解决
```
PS C:\Users\nceccy\Downloads\AVDC> .\Movie_Data_Capture.exe .\FC2-1267832-cd3.mp4
[*]================= Movie Data Capture =================
[*]                        6.0.1
[*]======================================================
[*] - Windows-10-10.0.19044-SP0
[*] - AMD64 - Python-3.8.10
[*]======================================================
[*] - 严禁在墙内宣传本项目 -
[*]======================================================
[+]Start at 2022-01-08 02:05:25
[+]Load Config file 'C:\Users\nceccy\Downloads\AVDC\config.ini'.
[!]CmdLine: .\FC2-1267832-cd3.mp4
[+]Main Working mode ## -: Single File ##
[+]==================== Single File =====================
[!] [FC2-1267832] As Number making data for '.\FC2-1267832-cd3.mp4'
[+]Find movie [FC2-1267832] metadata on website 'javdb'
[+]Image Downloaded! JAV_output\FC2-1267832-むっちりぱっつんお尻で漣ちゃん！愛情たっぷりえっちでらぶらぶ中出ししちゃうよっ！【個人撮影】\FC2-1267832-cd3-poster.jpg
[+]Image Downloaded! JAV_output\FC2-1267832-むっちりぱっつんお尻で漣ちゃん！愛情たっぷりえっちでらぶらぶ中出ししちゃうよっ！【個人撮影】\FC2-1267832-cd3-fanart.jpg
[+]Wrote!            JAV_output\FC2-1267832-むっちりぱっつんお尻で漣ちゃん！愛情たっぷりえっちでらぶらぶ中出ししちゃうよっ！【個人撮影】\FC2-1267832-cd3.nfo
[*]======================================================
Traceback (most recent call last):
  File "Movie_Data_Capture.py", line 585, in <module>
  File "Movie_Data_Capture.py", line 565, in main
UnboundLocalError: local variable 'folder_path' referenced before assignment
[13856] Failed to execute script 'Movie_Data_Capture' due to unhandled exception!
```

**Comment by lededev** [comment]
你的第一遍执行，使用的source_folder是C:\Users\nceccy\Downloads\AVDC\config.ini里面配置的，如果配置文件中source_folder的值不是`.`，那么不会刮削当前目录，如果你觉得修改ini配置文件太麻烦，可以加`-p .`执行参数，将source_folder用命令行参数覆盖为当前目录。

**Comment by nceccy** [comment]
> 你的第一遍执行，使用的source_folder是C:\Users\nceccy\Downloads\AVDC\config.ini里面配置的，如果配置文件中source_folder的值不是`.`，那么不会刮削当前目录，如果你觉得修改ini配置文件太麻烦，可以加`-p .`执行参数，将source_folder用命令行参数覆盖为当前目录。

```
source_folder=./
```
配置文件很久之前就写好了，同目录下其它将近100个文件都刮削完成了，就剩这些列出来的没有被处理

**Comment by lededev** [comment]
问题是你报的这bug没法重现啊，我按你列出的那些文件，跑了一遍，全部都能够识别。
只不过FC2需要有效的javdb cookies，才能得到内容。

> 配置文件很久之前就写好了，同目录下其它将近100个文件都刮削完成了，就剩这些列出来的没有被处理
