### ISSUE TITLE
路由器代理模式为绕过大陆IP，youtube正常，运行失败

### ISSUE THREAD

**Issue by wtjzjyh** [yoshiko2/Movie_Data_Capture#701]
cmd下显示如下：
[+]Load Config file 'C:\Users\Administrator\mdc.ini'.
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[-]Connect retry 1/3
[-]Connect retry 1/3
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 2/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Connect Failed! Please Check your proxy config
[-]Connect retry 3/3
[-]Connect retry 3/3
[-]Connect Failed! Please Check your proxy config
[-]Connect Failed! Please Check your proxy config
Traceback (most recent call last):
  File "Movie_Data_Capture.py", line 585, in <module>
  File "Movie_Data_Capture.py", line 511, in main
  File "ADC_function.py", line 506, in parallel_download_files
  File "concurrent\futures\_base.py", line 619, in result_iterator
  File "concurrent\futures\_base.py", line 444, in result
  File "concurrent\futures\_base.py", line 389, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "ADC_function.py", line 484, in download_one_file
  File "ADC_function.py", line 480, in _inner
  File "ADC_function.py", line 65, in get_html
Exception: Connect Failed
[8456] Failed to execute script 'Movie_Data_Capture' due to unhandled exception!

**Comment by YanYan233** [comment]
有解决方法么？
我这里好像不是代理的问题

[*]================= Movie Data Capture =================
[*]                        6.0.2
[*]======================================================
[*] - Windows-10-10.0.19042-SP0
[*] - AMD64 - Python-3.8.10
[*]======================================================
[*] - 严禁在墙内宣传本项目 -
[*]======================================================
[+]Start at 2022-03-05 22:28:10
[+]Load Config file '\\*************（路径，隐藏了）\config.ini'.
[+]Main Working mode ## 1: Scraping ## , multi_threading on
Traceback (most recent call last):
  File "Movie_Data_Capture.py", line 618, in <module>
  File "Movie_Data_Capture.py", line 524, in main
  File "Movie_Data_Capture.py", line 34, in check_update
KeyError: 'tag_name'
[6300] Failed to execute script 'Movie_Data_Capture' due to unhandled exception!
