### ISSUE TITLE
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch

### ISSUE THREAD

**Issue by 1kchen** [yoshiko2/Movie_Data_Capture#703]
Docker 6.0.1

**2022-02-20 03:11:02,stdout,[18] Failed to execute script 'Movie_Data_Capture' due to unhandled exception!

2022-02-20 03:11:02,stdout,"lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: input line 6 and body, line 7, column 12
"**
2022-02-20 03:11:02,stdout," File "/root/.local/share/mdc/mapping_actor.xml", line 7
"
2022-02-20 03:11:02,stdout," File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
"
2022-02-20 03:11:02,stdout," File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
"
2022-02-20 03:11:02,stdout," File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
"
2022-02-20 03:11:02,stdout," File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
"
2022-02-20 03:11:02,stdout," File "src/lxml/parser.pxi", line 1805, in lxml.etree._parseDocFromFile
"
2022-02-20 03:11:02,stdout," File "src/lxml/parser.pxi", line 1901, in lxml.etree._parseDocumentFromURL
"
2022-02-20 03:11:02,stdout," File "src/lxml/parser.pxi", line 1875, in lxml.etree._parseDocument
"
2022-02-20 03:11:02,stdout," File "src/lxml/etree.pyx", line 3536, in lxml.etree.parse
"
2022-02-20 03:11:02,stdout," File "WebCrawler/init.py", line 44, in get_data_from_json
"
2022-02-20 03:11:02,stdout," File "core.py", line 609, in core_main
"
2022-02-20 03:11:02,stdout," File "Movie_Data_Capture.py", line 394, in create_data_and_move
"
2022-02-20 03:11:02,stdout," File "Movie_Data_Capture.py", line 557, in main
"
2022-02-20 03:11:02,stdout," File "Movie_Data_Capture.py", line 585, in
"
2022-02-20 03:11:02,stdout,Traceback (most recent call last):

2022-02-20 03:11:02,stdout,[!] [VVV-068] As Number making data for '/data/VVV-068-02.mp4'

2022-02-20 03:11:02,stdout,[!] - 5.55% [1/18] - 03:11:02

2022-02-20 03:11:02,stdout,[*]======================================================

2022-02-20 03:11:02,stdout,[+]Find 18 movies.

2022-02-20 03:11:02,stdout,"[+]Main Working mode ## 1: Scraping ## , multi_threading on, nfo_skip_days=30
"
2022-02-20 03:11:02,stdout,[+]Enable debug

2022-02-20 03:11:02,stdout,[+]Load Config file '/root/mdc.ini'.

2022-02-20 03:11:02,stdout,[+]Start at 2022-02-20 03:11:02

2022-02-20 03:11:02,stdout,[*]======================================================

2022-02-20 03:11:02,stdout,[*] - 严禁在墙内宣传本项目 -

2022-02-20 03:11:02,stdout,[*]======================================================

2022-02-20 03:11:02,stdout,[*] - x86_64 - Python-3.8.12

2022-02-20 03:11:02,stdout,[*] - Linux-4.4.180+-x86_64-with

2022-02-20 03:11:02,stdout,[*]======================================================

2022-02-20 03:11:02,stdout,[*] 6.0.1

2022-02-20 03:11:02,stdout,[*]================= Movie Data Capture =================

**Comment by lededev** [comment]
xml文件是坏的，删掉mapping_actor.xml重新下载。
