### ISSUE TITLE
FC2刮削失败

### ISSUE THREAD

**Issue by qxzg** [yoshiko2/Movie_Data_Capture#776]
1. 确认javdb上有该影片的信息，但javdb刮削结果是`number not eq`（网络环境可直连javdb）：

```
 .\Movie_Data_Capture.exe .\FC2-607854.mp4 -g
[*]================= Movie Data Capture =================
[*]                        6.1.1
[*]======================================================
[*] - Windows-10-10.0.19043-SP0
[*] - AMD64 - Python-3.8.10
[*]======================================================
[*] - 严禁在墙内宣传本项目 -
[*]======================================================
[+]Start at 2022-04-23 16:46:36
[+]Load Config file 'xxxxxxxxx\config.ini'.
[+]Enable debug
[!]CmdLine: .\FC2-607854.mp4 -g
[+]Main Working mode ## -: Single File ##
[+]==================== Single File =====================
[!] [FC2-607854] As Number making data for '.\FC2-607854.mp4'
[+]select gcolle
[-]gcolle.py: number not match
[-]gcolle.py: number not match
[+]select javdb
[!]javdb:select site javdb32
number not eq
[+]select fc2
list index out of range
[+]select javbus
404 page not found
[+]select airav
404 page not found
list index out of range
[+]select fanza
[+]select xcity
list index out of range
[+]select mgstage
[+]select avsox
number not found
[+]select dlsite
list index out of range
[+]select carib
cannot unpack non-iterable NoneType object
[+]select madou
list index out of range
[+]select mv91
FC2-607854
local variable 'htmlcode' referenced before assignment
[-]Movie number has changed! [FC2-607854]->[None]
'[-]Move to Failed output folder, see 'xxxxxxxxx\where_was_i_before_being_moved.txt'
[*]======================================================
[+]Running time 0:00:26.294  End at 2022-04-23 16:47:02
[+]All finished!!!
```

2. 对于fc2上匹配到的，会抛出`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`错误

```
[!] [FC2-2787433] As Number making data for 'xxxxxxxxx\FC2-2787433.mp4'
[+]select gcolle
[-]gcolle.py: number not match
[-]gcolle.py: number not match
[+]select javdb
[!]javdb:select site javdb32
number not eq
[+]select fc2
[+]Find movie [FC2-2787433] metadata on website 'fc2'
Traceback (most recent call last):
  File "Movie_Data_Capture.py", line 710, in <module>
  File "Movie_Data_Capture.py", line 634, in main
  File "Movie_Data_Capture.py", line 460, in create_data_and_move
  File "core.py", line 729, in core_main
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[29360] Failed to execute script 'Movie_Data_Capture' due to unhandled exception!
```
以上两条问题均在更新`6.1.1-r2`后才出现，其他影片的刮削目前没有发现问题。

**Comment by lededev** [comment]
你用浏览器登录，搜到那个番号然后点进去就知道了，现在看详细信息需要VIP权限了，如果你的账号有VIP权限，倒是可以导出一份cookies来刮削到内容。

**Comment by yoshiko2** [comment]
javdb刮削FC2需要VIP账号

**Comment by lededev** [comment]
而且在FC官网查不到这个番号，所以不是程序的问题。

**Comment by qxzg** [comment]
多谢解答
但是第二个番号在fc2官网是有的，而且挂了日本梯子之后还是报`[-] int() argument must be a string, a bytes-like object or a number, not 'NoneType'`
浏览器可以正常打开页面https://adult.contents.fc2.com/article/2787433/

**Comment by lededev** [comment]
我是说第一个番号607854在fc官网没有。FC2-2787433我试过了用fc2可以刮削成功。
```
PS Z:\t> New-Item -Name FC2-2787433.mp4 -ItemType File
PS Z:\t> mdc -m3 -p .
[*]======================================================
[!]                - 100.% [1/1] -             20:35:06
[!] [FC2-2787433] As Number making data for 'Z:\t\FC2-2787433.mp4'
[+]Find movie [FC2-2787433] metadata on website 'fc2'
[+]Image Downloaded! FC2-2787433-fanart.jpg
[+]Successfully downloaded 10 extrafanarts.
[+]Image Cutted!     FC2-2787433-poster.jpg
[+]Wrote!            Z:\t\FC2-2787433.nfo
[*]======================================================
PS Z:\t> dir
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2022/4/23     20:35                extrafanart
-a----         2022/4/23     20:35          18278 FC2-2787433-fanart.jpg
-a----         2022/4/23     20:35          13832 FC2-2787433-poster.jpg
-a----         2022/4/23     20:35          18278 FC2-2787433-thumb.jpg
-a----         2022/4/23     20:34              0 FC2-2787433.mp4
-a----         2022/4/23     20:35           2294 FC2-2787433.nfo

```

**Comment by yoshiko2** [comment]
下载6.1.1-r3

**Comment by qxzg** [comment]
> 下载6.1.1-r3

新版本测试没问题了，非常感谢。
